### ISSUE TITLE
swiper组件存在问题的

### ISSUE THREAD

**Issue by zhouyujian** [dcloudio/UniApp#21]
swiper循环轮播到最后一张，返回第一张时候，画面会消失。1秒后才能继续正常显示
swiper缺少loop属性，是否开启循环。

audio不能进入后台播放，也不能跨页面播放，功能会被限制。哪怕是hbuilder打包的音乐都可以进入后台的。

uniapp有大小限制吗？跟快应用一样1M限制？
未来能满足开发综合性大应用需求吗？

fullscreen的全屏模式其实保留电池栏，背景透明更好。这也是APP中常见的方式，完全全屏化，反而感觉很奇怪。

**Comment by zhouyujian** [comment]
那目前貌似没用提供沉浸式写法？

video不可见时候暂停理解，但是音乐普遍的都可以在后台或者切换页面时候依然能够播放。

swiper建议加上loop属性~

**Comment by xiaoyucoding** [comment]
默认就是沉浸式的，真机运行的时候很明显可以看出效果。
audio 和 video 这些媒体组件，机制都是一样的。

**Comment by xiaoyucoding** [comment]
已修复 swiper 的问题，更新最新的 HBuilderX 即可。
